// <auto-generated />
using System;
using ClinicaVeterinaria.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicaVeterinaria.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211005144130_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("auxiliarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("veterinarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("auxiliarId");

                    b.HasIndex("veterinarioId");

                    b.ToTable("historiaClinicas");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.Mascota", b =>
                {
                    b.Property<int>("MascotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripción")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("MascotaId");

                    b.HasIndex("MascotaId")
                        .IsUnique();

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.Auxiliar", b =>
                {
                    b.HasBaseType("ClinicaVeterinaria.App.Dominio.Persona");

                    b.Property<string>("Especializacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoVeterinario")
                        .HasColumnType("int");

                    b.Property<DateTime>("HorarioLaboral")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenciaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Auxiliar");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.Owner", b =>
                {
                    b.HasBaseType("ClinicaVeterinaria.App.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.Veterinario", b =>
                {
                    b.HasBaseType("ClinicaVeterinaria.App.Dominio.Persona");

                    b.Property<string>("Especializacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Veterinario_Especializacion");

                    b.Property<int>("EstadoVeterinario")
                        .HasColumnType("int")
                        .HasColumnName("Veterinario_EstadoVeterinario");

                    b.Property<DateTime>("HorarioLaboral")
                        .HasColumnType("datetime2")
                        .HasColumnName("Veterinario_HorarioLaboral");

                    b.Property<string>("LicenciaProfesional")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Veterinario_LicenciaProfesional");

                    b.Property<int?>("MascotaId")
                        .HasColumnType("int");

                    b.HasIndex("MascotaId");

                    b.HasDiscriminator().HasValue("Veterinario");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.HistoriaClinica", b =>
                {
                    b.HasOne("ClinicaVeterinaria.App.Dominio.Auxiliar", "auxiliar")
                        .WithMany()
                        .HasForeignKey("auxiliarId");

                    b.HasOne("ClinicaVeterinaria.App.Dominio.Veterinario", "veterinario")
                        .WithMany()
                        .HasForeignKey("veterinarioId");

                    b.Navigation("auxiliar");

                    b.Navigation("veterinario");
                });

            modelBuilder.Entity("ClinicaVeterinaria.App.Dominio.Veterinario", b =>
                {
                    b.HasOne("ClinicaVeterinaria.App.Dominio.Mascota", "mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId");

                    b.Navigation("mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
